cargo-features = ["edition2024"]

[workspace]
exclude = ["./xtask"]

[profile.release]
lto = true # コンパイル時間が著しく長くなってしまう場合は無し

[package]
name = "main"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
# 202411から:
rpds = "=1.1.0"
rand_xorshift = "=0.3.0"
rand_xoshiro = "=0.6.0"
statrs = "=0.18.0"
# 202301から:
ac-library-rs = "=0.1.1"
once_cell = "=1.20.2"
static_assertions = "=1.1.0"
varisat = "=0.2.2"
memoise = "=0.3.2"
argio = "=0.2.0"
bitvec = "=1.0.1"
counter = "=0.6.0"
hashbag = "=0.1.12"
pathfinding = "=4.14.0"
recur-fn = "=2.2.0"
indexing = { version = "=0.4.1", features = ["experimental_pointer_ranges"] }
amplify = { version = "=4.8.0", features = ["c_raw", "rand", "stringly_conversions"] }
amplify_derive = "=4.0.1"
amplify_num = { version = "=0.5.3", features = ["std"] }
easy-ext = "=1.0.2"
multimap = "=0.10.0"
btreemultimap = "=0.1.1"
bstr = "=1.11.3"
az = "=1.2.1"
glidesort = "=0.1.2"
tap = "=1.0.1"
omniswap = "=0.1.0"
multiversion = "=0.8.0"
# 202004から続投:
num = "=0.4.3"
num-bigint = "=0.4.6"
num-complex = "=0.4.6"
num-integer = "=0.1.46"
num-iter = "=0.1.45"
num-rational = "=0.4.2"
num-traits = "=0.2.19"
num-derive = "=0.4.2"
ndarray = "=0.16.1"
nalgebra = "=0.33.2"
alga = "=0.9.3"
libm = "=0.2.11"
rand = "=0.9.0"
getrandom = "=0.3.0"
rand_chacha = "=0.9.0"
rand_core = "=0.9.0"
rand_hc = "=0.3.2"
rand_pcg = "=0.9.0"
rand_distr = "=0.4.3"
petgraph = "=0.7.1"
indexmap = "=2.7.1"
regex = "=1.11.1"
lazy_static = "=1.5.0"
ordered-float = "=4.6.0"
ascii = "=1.1.0"
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.14.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.13.0"
im-rc = "=15.1.0"
fixedbitset = "=0.5.7"
bitset-fixed = "=0.1.0"
proconio = { version = "=0.5.0", features = ["derive"] }
text_io = "=0.1.12"
rustc-hash = "=2.1.0"
smallvec = { version = "=1.13.2", features = ["const_generics", "const_new", "write", "union", "serde", "arbitrary"] }
