targets = [
    { triple = "x86_64-unknown-linux-gnu" },
]

[bans]
multiple-versions = "allow"
# クレートの中にはビルド時にcurl等でCのライブラリ(lib○○)を持って来てリンクすることがある。
# 今回のクレートのセットにはそのようなものは含まれていない。
# そのことを各build.rsを目視して確認した。
allow-build-scripts = [
    { name = "anyhow", version = "=1.0.70" }, # https://docs.rs/crate/anyhow/1.0.70/source/build.rs
    { name = "az", version = "1.2.1" }, # https://docs.rs/crate/az/1.2.1/source/build.rs
    { name = "im-rc", version = "=15.1.0" }, # https://docs.rs/crate/im-rc/15.1.0/source/build.rs
    { name = "indexmap", version = "=1.9.3" }, # https://docs.rs/crate/indexmap/1.9.3/source/build.rs
    { name = "libc", version = "=0.2.140" }, # https://docs.rs/crate/libc/0.2.140/source/build.rs
    { name = "libm", version = "=0.2.6" }, # https://docs.rs/crate/libm/0.2.6/source/build.rs
    { name = "log", version = "=0.4.17" }, # https://docs.rs/crate/log/0.4.17/source/build.rs
    { name = "memchr", version = "=2.5.0" }, # https://docs.rs/crate/memchr/2.5.0/source/build.rs
    { name = "num-bigint", version = "=0.4.3" }, # https://docs.rs/crate/num-bigint/0.4.3/source/build.rs
    { name = "num-complex", version = "=0.2.4" }, # https://docs.rs/crate/num-complex/0.2.4/source/build.rs
    { name = "num-integer", version = "=0.1.45" }, # https://docs.rs/crate/num-integer/0.1.45/source/build.rs
    { name = "num-iter", version = "=0.1.43" }, # https://docs.rs/crate/num-iter/0.1.43/source/build.rs
    { name = "num-rational", version = "=0.4.1" }, # https://docs.rs/crate/num-rational/0.4.1/source/build.rs
    { name = "num-traits", version = "=0.2.15" }, # https://docs.rs/crate/num-traits/0.2.15/source/build.rs
    { name = "paste", version = "=1.0.12" }, # https://docs.rs/crate/paste/1.0.12/source/build.rs
    { name = "proc-macro2", version = "=1.0.53" }, # https://docs.rs/crate/proc-macro2/1.0.53/source/build.rs
    { name = "proc-macro-error", version = "=1.0.4" }, # https://docs.rs/crate/proc-macro-error/1.0.4/source/build.rs
    { name = "proc-macro-error-attr", version = "=1.0.4" }, # https://docs.rs/crate/proc-macro-error-attr/1.0.4/source/build.rs
    { name = "quote", version = "=1.0.26" }, # https://docs.rs/crate/quote/1.0.26/source/build.rs
    { name = "radium", version = "=0.7.0" }, # https://docs.rs/crate/radium/0.7.0/source/build.rs
    { name = "serde", version = "=1.0.158" }, # https://docs.rs/crate/serde/1.0.158/source/build.rs
    { name = "serde_derive", version = "=1.0.158" }, # https://docs.rs/crate/serde_derive/1.0.158/source/build.rs
    { name = "syn", version = "=1.0.109" }, # https://docs.rs/crate/syn/1.0.109/source/build.rs
    { name = "thiserror", version = "=1.0.40" }, # https://docs.rs/crate/thiserror/1.0.40/source/build.rs
    { name = "typenum", version = "=1.16.0" }, # https://docs.rs/crate/typenum/1.16.0/source/build/main.rs
    { name = "varisat", version = "=0.2.2" }, # https://docs.rs/crate/varisat/0.2.2/source/build.rs
]

[sources]
allow-git = [
    "https://github.com/rust-lang-ja/ac-library-rs.git",
]

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",

    "LicenseRef-AtCoderJudgeSystem",
]
clarify = [
    # https://github.com/EmbarkStudios/cargo-deny/issues/282
    # `judge`自体もライセンスを持つことを要求してくるため、ダミーのライセンスを宣言する
    # ac-library-rsも`package.private = true`であるため、上記リンクの方法は取れない
    { name = "judge", expression = "LicenseRef-AtCoderJudgeSystem", license-files = [] },
]
