name: Licenses

on:
  push:

jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Read ./rust-toolchain
        id: read-rust-toolchain
        run: echo "toolchain=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.read-rust-toolchain.outputs.toolchain }}

      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo-deny
        run: cargo binstall cargo-deny@^0.16 --no-confirm --log-level debug

      - name: cargo-deny (main)
        run: cargo deny check
      # https://github.com/EmbarkStudios/cargo-deny/pull/626 # Pixar ライセンスを無視するworkaround
      # https://github.com/jpeddicord/askalono/issues/94

  bottlerocket-license-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Read ./rust-toolchain
        id: read-rust-toolchain
        run: echo "toolchain=$(cat ./rust-toolchain)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.read-rust-toolchain.outputs.toolchain }}

      - name: Install bottlerocket-license-scan
        run: cargo install bottlerocket-license-scan --git https://github.com/bottlerocket-os/bottlerocket-sdk

      - name: bottlerocket-license-scan (main)
      # spdx-license-list v3.23 以降、 Apache-2.0 のバリエーション Pixar ライセンスが追加されたことにより、
      # rust-lang/rust のような appendix 無しの Apache-2.0 ライセンスを、 Pixar として誤って分類される問題が発生しています。
      # そのため、 SPDX License List Data v3.22 を使用して、 SPDX License List Data v3.23 以降の問題を回避します。
      # ただし、 SPDX License List Data v3.22 には、 SPDX License List Data v3.23 以降のライセンスが含まれていません。
      # （例えば unicode-ident@1.0.14 以降の Unicode-3.0 ライセンス。このため Unicode-DFS-2016 ライセンス の unicode-ident@1.0.13 で Lock しています。）
      # https://github.com/bottlerocket-os/bottlerocket-sdk/tree/develop/license-scan # 2024-12現在、この問題の影響あり
      # https://github.com/jpeddicord/askalono/issues/94
        run: |
          git clone https://github.com/spdx/license-list-data.git /tmp/license-list-data --depth 1 -b v3.22
          ~/.cargo/bin/bottlerocket-license-scan --clarify ./clarify.toml --out-dir ./license_files --spdx-data /tmp/license-list-data/json/details cargo ./Cargo.toml
          tree ./license_files
